powerdata <- read.table("C:/Users/Deepti/Documents/GettingandCleaningData/household_power_consumption.txt", header = TRUE, sep= ";",na.string = "?")
reqddata <- subset(powerdata, Date %in% c("1/2/2007", "2/2/2007" ))
datetime <- paste(as.Date(reqddata$Date,"%d/%m/%Y"), reqddata$Time)
reqddata$Datetime <- as.POSIXct(datetime)
par(mfrow=c(2,2))
with(reqddata,  plot(Global_active_power~Datetime, type="l", ylab="Global Active Power", xlab=""))
with(reqddata,  plot(Voltage~Datetime, type="l", ylab="Voltage", xlab="datetime"))
with(reqddata, plot(Sub_metering_1~Datetime, type="l", ylab="Energy sub metering", xlab="") )
lines(reqddata$Sub_metering_2~reqddata$Datetime, col="red")
lines(reqddata$Sub_metering_3~reqddata$Datetime, col="blue")
legend("topright", lty= 1, lwd =2 , col = c("black", "red", "blue"), legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3" ), cex = 0.75)
with(reqddata,  plot(Global_reactive_power~Datetime, type="l", xlab="datetime")) 
dev.copy(png, "plot4.png", width=480, height= 480) 
dev.off()